# Generated by Django 3.0.6 on 2020-05-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'verbose_name_plural': 'Breweries'},
        ),
        migrations.AlterModelOptions(
            name='hops',
            options={'verbose_name_plural': 'Hops'},
        ),
        migrations.AlterField(
            model_name='review',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beers.Beer'),
        ),
    ]
