# Generated by Django 3.0.6 on 2020-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20200507_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='abv'),
        ),
    ]
