# Generated by Django 3.0.6 on 2020-05-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_auto_20200510_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='style',
            new_name='styles',
        ),
    ]
